name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build shared package
        run: npm run build -w @app-disparo/shared

      - name: Lint
        run: npm run lint --if-present

      - name: Build server
        run: npm run build -w apps/server

      - name: Build client
        run: npm run build -w apps/client

      - name: Prisma generate (server)
        run: npm run prisma:generate -w @app-disparo/server || true

